### ISSUE TITLE
Administrator do not know if an user has been blocked. 

### ISSUE THREAD

**Issue by Pablohn26** [midnightSuyama/redmine_login_attempts_limit#1]
First of all, thanks for your plugin.

I have installed it and I have tried the plugin but I have a problem.

I have created a new test account with internal login (I also have native LDAP authentication).

The test user could login and then I have tried wrong passwords till I get "This account has been blocked, please try again later." The problem from an admin perspective is that administrator do not know if an user has been blocked. The test user gets an email notification but the admin do not.

To provide that, I suggest: 

- Send an email to custom notification address
- Provide a list of blocked users on configuration panel.

**Comment by midnightSuyama** [comment]
The cause of not sent is https://github.com/redmine/redmine/blob/3.3.2/app/models/mailer.rb#L464-L469 .

Fixed https://github.com/midnightSuyama/redmine_login_attempts_limit/commit/8a9c9ac1e1e1a180fb01991cb7c48e80dedfd86e .

Thanks :)

**Comment by bluekyg** [comment]
below issue not showing...

Provide a list of blocked users on configuration panel.
